-- Inserindo 50 equipamentos
INSERT INTO equipamentos (nome, numero_serie, tipo, dh_cadastro) VALUES
('Motor Elétrico', 'SN001', 'Mecânico', NOW()),
('Bomba Hidráulica', 'SN002', 'Hidráulico', NOW()),
('Gerador Diesel', 'SN003', 'Elétrico', NOW()),
('Turbina a Gás', 'SN004', 'Mecânico', NOW()),
('Transformador', 'SN005', 'Elétrico', NOW()),
('Esteira Transportadora', 'SN006', 'Mecânico', NOW()),
('Caldeira Industrial', 'SN007', 'Térmico', NOW()),
('Compressores de Ar', 'SN008', 'Mecânico', NOW()),
('Painel Elétrico', 'SN009', 'Elétrico', NOW()),
('Sensor de Pressão', 'SN010', 'Eletrônico', NOW()),
('Motor Elétrico', 'SN011', 'Mecânico', NOW()),
('Bomba de Vácuo', 'SN012', 'Hidráulico', NOW()),
('Gerador Fotovoltaico', 'SN013', 'Elétrico', NOW()),
('Forno Industrial', 'SN014', 'Térmico', NOW()),
('Elevador de Carga', 'SN015', 'Mecânico', NOW()),
('Ventilador Industrial', 'SN016', 'Mecânico', NOW()),
('Sistema de Refrigeração', 'SN017', 'Térmico', NOW()),
('Inversor de Frequência', 'SN018', 'Eletrônico', NOW()),
('Chiller Industrial', 'SN019', 'Térmico', NOW()),
('Bancada de Testes', 'SN020', 'Eletrônico', NOW()),
('Máquina de Solda', 'SN021', 'Elétrico', NOW()),
('Caminhão Guindaste', 'SN022', 'Mecânico', NOW()),
('Torre de Resfriamento', 'SN023', 'Térmico', NOW()),
('Retificador de Tensão', 'SN024', 'Elétrico', NOW()),
('Sistema de Iluminação', 'SN025', 'Elétrico', NOW()),
('CNC Torno', 'SN026', 'Mecânico', NOW()),
('Prensa Hidráulica', 'SN027', 'Hidráulico', NOW()),
('Válvula de Controle', 'SN028', 'Hidráulico', NOW()),
('Redutor de Velocidade', 'SN029', 'Mecânico', NOW()),
('Sistema de Supervisão', 'SN030', 'Eletrônico', NOW()),
('Bateria Estacionária', 'SN031', 'Elétrico', NOW()),
('Estação Meteorológica', 'SN032', 'Eletrônico', NOW()),
('Reator Químico', 'SN033', 'Químico', NOW()),
('Sensor de Vibração', 'SN034', 'Eletrônico', NOW()),
('Disjuntor de Potência', 'SN035', 'Elétrico', NOW()),
('Gerador de Vapor', 'SN036', 'Térmico', NOW()),
('Tanque de Armazenamento', 'SN037', 'Mecânico', NOW()),
('Motor Diesel', 'SN038', 'Mecânico', NOW()),
('Placa Controladora', 'SN039', 'Eletrônico', NOW()),
('Drone Inspeção', 'SN040', 'Eletrônico', NOW()),
('Microturbina', 'SN041', 'Mecânico', NOW()),
('Gerador Eólico', 'SN042', 'Elétrico', NOW()),
('Conversor de Energia', 'SN043', 'Eletrônico', NOW()),
('Sistema de CFTV', 'SN044', 'Eletrônico', NOW()),
('Chave Seccionadora', 'SN045', 'Elétrico', NOW()),
('Moinho Industrial', 'SN046', 'Mecânico', NOW()),
('Fresadora CNC', 'SN047', 'Mecânico', NOW()),
('Sensor de Temperatura', 'SN048', 'Eletrônico', NOW()),
('Plataforma Elevatória', 'SN049', 'Mecânico', NOW()),
('Esteira de Rolos', 'SN050', 'Mecânico', NOW());

-- Inserindo 30 alarmes com situação "I" (Inativo)
INSERT INTO alarmes (equipamento_id, descricao, situacao, classificacao, dh_cadastro) VALUES
(5, 'Falha no isolamento térmico', 'I', 'Aviso', NOW()),
(12, 'Baixa pressão no sistema', 'I', 'Alerta', NOW()),
(8, 'Falha na compressão de ar', 'I', 'Aviso', NOW()),
(25, 'Oscilação de tensão detectada', 'I', 'Aviso', NOW()),
(17, 'Resfriamento ineficiente', 'I', 'Aviso', NOW()),
(36, 'Nível baixo de combustível', 'I', 'Aviso', NOW()),
(21, 'Sobreaquecimento no transformador', 'I', 'Aviso', NOW()),
(9, 'Variação de corrente inesperada', 'I', 'Aviso', NOW()),
(14, 'Acúmulo de resíduos no forno', 'I', 'Aviso', NOW()),
(29, 'Desgaste anormal no redutor', 'I', 'Aviso', NOW()),
(41, 'Eficiência reduzida na microturbina', 'I', 'Alerta', NOW()),
(11, 'Baixo nível de lubrificação', 'I', 'Aviso', NOW()),
(48, 'Leitura instável do sensor de temperatura', 'I', 'Aviso', NOW()),
(33, 'Reação química inesperada', 'I', 'Alerta', NOW()),
(19, 'Falha no monitoramento de nível', 'I', 'Aviso', NOW()),
(27, 'Pressão excessiva na prensa hidráulica', 'I', 'Aviso', NOW()),
(45, 'Problema na chave seccionadora', 'I', 'Aviso', NOW()),
(39, 'Falha na comunicação da placa controladora', 'I', 'Alerta', NOW()),
(4, 'Temperatura elevada na turbina', 'I', 'Aviso', NOW()),
(30, 'Falha na comunicação do SCADA', 'I', 'Aviso', NOW()),
(16, 'Ventilação insuficiente no motor', 'I', 'Aviso', NOW()),
(50, 'Desgaste no rolamento da esteira', 'I', 'Aviso', NOW()),
(44, 'Câmera de monitoramento inoperante', 'I', 'Aviso', NOW()),
(28, 'Obstrução parcial na válvula de controle', 'I', 'Aviso', NOW()),
(7, 'Pressão acima do normal na caldeira', 'I', 'Aviso', NOW()),
(23, 'Torre de resfriamento com fluxo reduzido', 'I', 'Aviso', NOW()),
(37, 'Dificuldade na ignição do gerador', 'I', 'Aviso', NOW()),
(31, 'Bateria em nível crítico', 'I', 'Alerta', NOW()),
(22, 'Carga excedendo limite recomendado', 'I', 'Aviso', NOW()),
(3, 'Baixa tensão no gerador', 'I', 'Aviso', NOW());
