services:
  app:
    container_name: php_app
    image: php:8.2-apache
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    restart: always
    depends_on:
      - db

  db:
    container_name: mysql_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_alarmes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/database/migrations:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"  # phpMyAdmin rodará em http://localhost:8081
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_ABSOLUTE_URI: http://localhost:8081/
      PMA_FORCE_SSL: false
      PHP_INI_SESSION__COOKIE_SECURE: 0

volumes:
  db_data: